/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3b190c92bdafc2fd51d2e7a274677332)
declare namespace Cloudflare {
	interface Env {
		VISITOR_COUNTER: KVNamespace;
		ALLOWED_ORIGIN: "https://si3rraquack.github.io";
	}
}
interface Env extends Cloudflare.Env {}

